### ISSUE TITLE
GitHub identity not set

### ISSUE THREAD

**Issue by lmrodriguezr** [cadwallion/publish-rubygems-action#9]
Hello!

First off, thank you very much for this very useful action!

I'm having an issue with my repository, though. When I execute it, I'm getting this error:

```
rake aborted!

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@524cc3ea82ce.(none)')

Tasks: TOP => release => release:source_control_push
(See full trace by running task with --trace)

```

(see [here](https://github.com/bio-miga/miga/runs/1971462940?check_suite_focus=true))

I'm passing the `GITHUB_TOKEN` secret, but this repository is hosted by an organization, not a user. Could that be the reason? This is the action configuration in case that helps:
https://github.com/bio-miga/miga/blob/main/.github/workflows/build.yml#L36

Thanks!

**Comment by CvX** [comment]
The issue here is not with GitHub but git. 🙂

`rake release` is trying to create a git tag but is unable to do so when `git config --global user.email` and `git config --global user.name` are not set.

That usually is not a problem when using publish-rubygems-action since the recommended (in README) flow is to run the action on tag push – then `rake release` sees that the tag is already present and skips this part. 😃 

You could probably work around it by adding those git commands to the workflow:

```yml
- name: Tag and deploy
  if: steps.changed-version.outputs.changed == 'true'
  uses: cadwallion/publish-rubygems-action@master
  env:
    RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    RELEASE_COMMAND: |
      git config --global user.email "automated@example.com"
      git config --global user.name "Automated Release"
      bundle exec rake release
```
